### ISSUE TITLE
No way to circumvent "ensure-clean" check, which always fails

### ISSUE THREAD

**Issue by zilti** [adzerk/bootlaces#3]
There should be a way to circumvent the "ensure-clean" check. It's impossible to push that way, since the repo is never clean at the stage it is checked.

**Comment by alandipert** [comment]
I'm not sure why it would be that your repo is never clean - perhaps you need a .gitignore?

In any case, it is possible to circumvent this behavior.  The `bootlaces!` functions calls `task-options!` and [sets the `push` built-in task's `:ensure-clean` argument to `true`](https://github.com/adzerk/bootlaces/blob/aba490d2737eb092e6efb1f4095b94946a14fb20/src/adzerk/bootlaces.clj#L18).

You can revert this configuration by calling `task-options!` again in your `build.boot` after the `bootlaces!` call.  For example:

    (task-options! push {:ensure-clean false})

Is this helpful, or is your problem something different?

**Comment by zilti** [comment]
In the end it was a hidden file which was not even in the .gitignore which the git function to clean ignored anyway, but bootlaces did not. Ok, this task option helps, good to know.

**Comment by crisptrutski** [comment]
Is there a way to set this value from CLI usage? Feels a bit hacky editing `build.boot` (or even `profiles.boot`) for this 

Some ideas if there isn't: `BOOT__PUSH__ENSURE_CLEAN=true boot push-release` or `boot -o '{:push {:ensure-clean true}}' push-release`

Or proxy `push` options via the `push-*` tasks. 

Or, one last late night idea: support generic dynamic-scope style default setting via namespaced keyword arguments: `(push-release :push/ensure-clean false)`. That would be a pretty cool way to get lots of extra knobs in useful plans, and give a sweet CLI syntax too (aside from escaping forward slashes)
