### ISSUE TITLE
Creates tag before successful deploy

### ISSUE THREAD

**Issue by zilti** [adzerk/bootlaces#6]
Bootlaces already creates the git tag before the deploy to clojars is successful. Should it fail, subsequent tries will fail due to the already-existing tag.

**Comment by micha** [comment]
I'm not sure we want boot to be deleting tags itself, do we? I'm not sure what the correct behavior is when the clojars thing fails.

**Comment by zilti** [comment]
I'd suggest to create the tag *after* the clojars deploy has been successful.

**Comment by micha** [comment]
Haha, oh right. That makes sense.
